[language-server.docker-language-server]
command = "docker-language-server"
args = []

[language-server.fortls]
command = "fortls"
args = ["--symbol_skip_mem", "--incremental_sync", "--autocomplete_no_prefix", "--lowercase_intrinsics", "--hover_signature", "--use_signature_help"]
config = { provideFormatter = true }

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.json.path=stdout", "--show-stats=false", "--issues-exit-code=1"]


[[language]]
name = "fortran"
auto-format = true
formatter = { command = "fprettify", args = ["--silent"]}
# language-servers = ["fortls"]
language-servers = [ { name = "fortls" } ]

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "go"
auto-format = true
formatter = { command = "gofmt" }

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "swift"
auto-format = true
formatter = { command = "swift-format" }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black"}
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pylint.enabled = true
plugins.pyflakes.enabled = false
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "4"] }
language-servers = [ { name = "docker-language-server" } ]
